config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  # ADMIN routes
  #
  namespace :admin do
    root 'home#index'
    ## Users - >
    resources :users do
      get :dashboard
    end
  end

  # Devise
  # devise_for :users, path: 'admin', path_names: { sign_in: 'login'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/admin/application_controller.rb
require_relative 'concerns/authentication'

class Admin::ApplicationController < ApplicationController
  include Common
  layout 'admin/layouts/admin'
  # include Common
  # Manipular excessões com :log_exception_handler
  # rescue_from Exception, with: :log_exception_handler unless Rails.env.development?
  # self.exception_data = Proc.new { |controller| controller.current_user ? "#{controller.current_user.login} - #{controller.current_user.nome}" : "" } unless Rails.env.development?

  # Manipular excessões de permissões do CanCanCan
  rescue_from CanCan::AccessDenied do
    redirect_to admin_root_url, alert: t('views.responses.acess_denied')
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
  # GET /
  def index; end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :load_references, only: [:show, :new, :create, :edit, :update, :destroy]
  load_and_authorize_resource only: [:index, :show, :new, :edit, :create, :update, :destroy]

  decorates_assigned :users

  # GET /admin/users or /admin/users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 25)
  end

  # GET /admin/users/1 or /admin/users/1.json
  def show; end

  # GET /admin/users/new
  def new
    @user = User.new
    @user.build_user_profile
  end

  # GET /admin/users/1/edit
  def edit; end

  # POST /admin/users or /admin/users.json
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: t('views.users.form.create')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /admin/users/1 or /admin/users/1.json
  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: t('views.users.form.update')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/users/1 or /admin/users/1.json
  def destroy
    @user.destroy!
    redirect_to admin_users_url, notice: t('views.users.form.destroy')
  end

  private

  def load_references
    @profiles = Profile.order(description: :asc)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id] || params[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    temp_params = params.require(:user).permit(
      :uid,
      :active,
      :name,
      :login,
      :email,
      :password,
      :password_confirmation,
      :extern,
      user_profile_attributes: [
        :id,
        :profile_id
      ]
    )
    return temp_params if temp_params[:password].present?
    temp_params.except(:password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
require_relative 'concerns/authentication'

class Admin::ApplicationController < ApplicationController
  include Admin::Concerns::Authentication
  include Common
  layout 'admin/layouts/admin'
  # include Common

  # Manipular excessões com :log_exception_handler
  # rescue_from Exception, with: :log_exception_handler unless Rails.env.development?
  # self.exception_data = Proc.new { |controller| controller.current_user ? "#{controller.current_user.login} - #{controller.current_user.nome}" : "" } unless Rails.env.development?

  # Manipular excessões de permissões do CanCanCan
  rescue_from CanCan::AccessDenied do
    redirect_to admin_root_url, alert: t('views.responses.acess_denied')
  end
end

app/controllers/concerns/commom.rb
module Common
  def params_per_page(per_page, max_value = 100)
    if per_page.to_i.between?(1, max_value.to_i)
      per_page.to_i
    elsif per_page.to_i > max_value
      max_value
    else
      30
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home/context.html.erb
<%= render 'admin/layouts/partials/messages' %>

<% title t('views.home.context.title')%>

<%= form_for(@current_user, url: admin_context_path, html: { autocomplete: 'off' }) do |form| %>
  <div class="card">
    <div class="card-header">
      <%= t('views.home.context.user_context') %>
    </div>
    <div class="card-body">
      <div class="form-group">
        <%= form.select :context_id, options_from_collection_for_select(current_user.contexts, :id, :description, form.object.context_id), { include_blank: true }, class: 'form-control chosen-select' %>
      </div>
    </div>
    <div class="card-footer text-center">
      <%= form.button class: 'btn btn-primary', url: admin_context_path do %> <i class="fa fa-check"></i> <%= t('views.buttons.save') %><% end %>
    </div>
  </div>
<% end -%>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="<%= locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="turbolinks-cache-control" content="no-cache">
    <title><%= content_for?(:title) ? "#{yield(:title)} - CPA - Claretiano" : 'CPA - Claretiano - Rede de Educação' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :stylesheets %>

    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'admin/select_fields/style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'replies/index', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129898101-4%22%3E"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-129898101-4');
    </script>
    <link rel="icon" href="/favicon.ico" />
  </head>
  <body class="<%= controller_path.gsub('admin', '').parameterize.gsub('_', '-') %>">
    <div class="wrapper">
      <header class="navbar-header">
        <div class="navbar-brand">
          <div class="brand-logo">
            <%= image_tag 'admin/claretiano-189x43' %>
          </div>
        </div>
        <div class="navbar-content">
          <%= yield :title %>
        </div>
        <div class="navbar-dropdowns">
          <nav class="navbar navbar-expand-sm">
            <div class="collapse navbar-collapse">
              <ul class="navbar-nav">
                <li class="nav-item user-notifications bg-blue2">
                  <%= link_to '#', class: 'nav-link dropdown-toggle', 'data-bs-toggle' => 'dropdown' do %>
                    <em class="fa fa-ticket notificacao-icon mr-sm"></em> Tickets
                  <% end %>
                  <div class="dropdown-menu">
                    <%= link_to 'https://claretiano.freshservice.com/support/tickets', class: 'dropdown-item', target: '_blank' do %>
                      <em class="fa fa-user mr-sm"></em> Meus tickets
                    <% end %>
                    <%= link_to 'https://claretiano.freshservice.com/support/tickets/new', class: 'dropdown-item', target: '_blank' do %>
                      <em class="fa fa-plus mr-sm"></em> Abrir ticket
                    <% end %>
                    <%= link_to 'https://claretiano.freshservice.com/support/home', class: 'dropdown-item', target: '_blank' do %>
                      <em class="fa fa-laptop mr-sm"></em> Central de Serviços
                    <% end %>
                  </div>
                </li>
                <li class="nav-item dropdown user-settings">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="user-info">
                      <p class="user-name">
                        <%= current_user.name %>
                      </p>
                      <p class="user-context">
                        <%= current_user.context&.description || 'Contexto não selecionado' %>
                      </p>
                    </div>
                    <div class="user-photo">
                      <%= image_tag 'admin/usuario-200x200.png', alt: current_user.name, title: current_user.name %>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown-menu-end" id="dropdown-user" style="width: 400px">
                    <div class="dropdown-item">
                      <div class="row">
                        <div class="col-4 pr0">
                          <div class="user-photo">
                            <%= image_tag 'admin/usuario-200x200.png', alt: current_user.name, title: current_user.name %>
                          </div>
                        </div>
                        <div class="col-8 pl0">
                          <div class="user-info">
                            <p><strong><%= current_user.name %></strong></p>
                            <p><small><%= current_user.login %> - <%= current_user.email %></small></p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="dropdown-divider"></div>
                    <%= link_to admin_my_contexts_path(location: request.path), class: 'dropdown-item', remote: true do %>Alterar contexto de trabalho<% end %>
                    <div class="dropdown-divider"></div>
                    <%= link_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %>Sair<% end %>
                  </div>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </header>
      <aside class="left-menu">
        <div class="aside-inner">
          <nav class="sidebar">
            <div class="sidebar-search">
              <%= form_tag 'javascript:void(0)', method: 'get', id: 'form-sidebar-search' do%>
                <div class="input-group search">
                  <div class="input-group-prepend">
                    <%= button_tag class: 'btn btn-primary' do %><i class="fa fa-search"></i><% end %>
                  </div>
                  <%= text_field_tag :search_menu_item, '', class: 'form-control', placeholder: 'Pesquisar', autocomplete: 'off' %>
                </div>
              <% end %>
            </div>
            <ul class="nav" id="left-menu-accordion">
              <li class="nav-heading">
                <%= link_to admin_root_path do %><%= fa_icon "tachometer" %> Dashboard <% end %>
              </li> 
              <% if can?(:read, User) %>
                <li class="nav-heading">
                  <span data-bs-toggle="collapse" data-bs-target="#collapse-menu-administracao" aria-expanded="false">
                    <%= fa_icon "gear" %> Administração <i class="fa fa-angle-down arrow"></i>
                  </span>
                  <ul class="collapse collapsed" id="collapse-menu-administracao">
                    <% if can? :read, User %><li><%= link_to admin_users_path do %><em class="fa fa-caret-right"></em> <span>Usuários</span><% end %></li><% end %>
                  </ul>
                </li>
              <% end %>
              <% if can?(:read, Question) || can?(:read, Questionnaire) || can?(:read, Dimension) %>
                <li class="nav-heading">
                  <span data-bs-toggle="collapse" data-bs-target="#collapse-menu-cadastro-questionarios" aria-expanded="false">
                    <%= fa_icon "file" %> Cadastro de Questionário <i class="fa fa-angle-down arrow"></i>
                  </span>
                  <ul class="collapse collapsed" id="collapse-menu-cadastro-questionarios">
                    <% if can? :read, Question %><li><%= link_to admin_questions_path do %><em class="fa fa-caret-right"></em> <span>Questões</span><% end %></li><% end %>
                    <% if can? :read, Questionnaire %><li><%= link_to admin_questionnaires_path do %><em class="fa fa-caret-right"></em> <span>Questionários</span><% end %></li><% end %>
                    <% if can? :read, Dimension %><li><%= link_to admin_dimensions_path do %><em class="fa fa-caret-right"></em> <span>Dimensões</span><% end %></li><% end %>
                  </ul>
                </li>
              <% end %>
              <% if can?(:read, QuestionnairePeriod) || can?(:manage, :report) %>
                <li class="nav-heading">
                  <span data-bs-toggle="collapse" data-bs-target="#collapse-q-period-application" aria-expanded="false">
                    <%= fa_icon "calendar" %> Periodo de Aplicação  <i class="fa fa-angle-down arrow"></i>
                  </span>
                  <ul class="collapse collapsed" id="collapse-q-period-application">
                    <% if can? :read, QuestionnairePeriod %><li><%= link_to admin_questionnaire_periods_path do %><em class="fa fa-caret-right"></em> <span>Períodos</span><% end %></li><% end %>
                  </ul>
                </li>
                <li class="nav-heading">
                  <span data-bs-toggle="collapse" data-bs-target="#collapse-menu-relatorios" aria-expanded="false">
                    <%= fa_icon "bar-chart" %> Relatórios <i class="fa fa-angle-down arrow"></i>
                  </span>
                  <ul class="collapse collapsed" id="collapse-menu-relatorios">
                    <% if can? :read, :report %><li><%= link_to admin_reports_path do %><em class="fa fa-caret-right"></em> <span>Relatórios</span><% end %></li><% end %>
                  </ul>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </aside>

      <section>
        <div class="content-wrapper" >
          <%= yield %>
        </div>
      </section>

      <div id="modal-holder"></div>

      <div class="app-loading">
        <div style="display: block"></div>
      </div>

    </div>
    <%= yield :javascripts %>
  </body>
</html>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cpa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/admin/layouts/partials/_content.html.erb
<section>
  <div class="content-wrapper" >
    <%= yield %>
  </div>
</section>

app/views/admin/layouts/partials/_cookie_consent.html.erb
<link rel="stylesheet" type="text/css" href="https://privacidade.redeclaretiano.edu.br/assets/css/cookie_consent.css" />
<script src="https://privacidade.redeclaretiano.edu.br/assets/js/cookie_consent.js" data-cfasync="false"></script>
<script src="https://privacidade.redeclaretiano.edu.br/assets/js/parametrizacao.js" data-cfasync="false"></script>

app/views/admin/layouts/partials/_header.html.erb
<header class="navbar-header">
  <div class="navbar-brand">
    <div class="brand-logo">
      <%= image_tag 'admin/claretiano-189x43' %>
    </div>
  </div>
  <div class="navbar-content">
    <%= yield :title %>
  </div>
  <div class="navbar-dropdowns">
    <nav class="navbar navbar-expand-sm">
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item user-notifications bg-blue2">
            <%= link_to '#', class: 'nav-link dropdown-toggle', 'data-bs-toggle' => 'dropdown' do %>
              <em class="fa fa-ticket notificacao-icon mr-sm"></em> Tickets
            <% end %>
            <div class="dropdown-menu">
              <%= link_to 'https://claretiano.freshservice.com/support/tickets', class: 'dropdown-item', target: '_blank' do %>
                <em class="fa fa-user mr-sm"></em> Meus tickets
              <% end %>
              <%= link_to 'https://claretiano.freshservice.com/support/tickets/new', class: 'dropdown-item', target: '_blank' do %>
                <em class="fa fa-plus mr-sm"></em> Abrir ticket
              <% end %>
              <%= link_to 'https://claretiano.freshservice.com/support/home', class: 'dropdown-item', target: '_blank' do %>
                <em class="fa fa-laptop mr-sm"></em> Central de Serviços
              <% end %>
            </div>
          </li>
          <li class="nav-item dropdown user-settings">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="user-info">
                <p class="user-name">
                  <%= current_user.name %>
                </p>
                <p class="user-context">
                  <%= current_user.context&.description || 'Contexto não selecionado' %>
                </p>
              </div>
              <div class="user-photo">
                <%= image_tag 'admin/usuario-200x200.png', alt: current_user.name, title: current_user.name %>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-end" id="dropdown-user" style="width: 400px">
              <div class="dropdown-item">
                <div class="row">
                  <div class="col-4 pr0">
                    <div class="user-photo">
                      <%= image_tag 'admin/usuario-200x200.png', alt: current_user.name, title: current_user.name %>
                    </div>
                  </div>
                  <div class="col-8 pl0">
                    <div class="user-info">
                      <p><strong><%= current_user.name %></strong></p>
                      <p><small><%= current_user.login %> - <%= current_user.email %></small></p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="dropdown-divider"></div>
              <%= link_to admin_my_contexts_path(location: request.path), class: 'dropdown-item', remote: true do %>Alterar contexto de trabalho<% end %>
              <div class="dropdown-divider"></div>
              <%= link_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %>Sair<% end %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/admin/layouts/partials/_loading.html.erb
<div class="app-loading">
  <div style="display: block"></div>
</div>

app/views/admin/layouts/partials/_messages.html.erb
<div class="alert" role="alert" style="display: none;" id="alert">
  <button type="button" class="btn-close" onclick="$(this).parent().fadeOut();"></button>
  <span></span>
</div>
<% if defined?(object) && object && object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
      </div>
    <% elsif msg.is_a?(Array) && msg.any? %>
      <div class="alert alert-danger">
        <ul>
          <% msg.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% flash.discard(name) %>
  <% end %>
<% end %>

app/views/admin/layouts/partials/_modal.html.erb
<div id="modal-holder"></div>

app/views/admin/layouts/partials/_sidebar.html.erb
<aside class="left-menu">
  <div class="aside-inner">
    <nav class="sidebar">
      <div class="sidebar-search">
        <%= form_tag 'javascript:void(0)', method: 'get', id: 'form-sidebar-search' do%>
          <div class="input-group search">
            <div class="input-group-prepend">
              <%= button_tag class: 'btn btn-primary' do %><i class="fa fa-search"></i><% end %>
            </div>
            <%= text_field_tag :search_menu_item, '', class: 'form-control', placeholder: 'Pesquisar', autocomplete: 'off' %>
          </div>
        <% end %>
      </div>
      <ul class="nav" id="left-menu-accordion">
        <li class="nav-heading">
          <%= link_to admin_root_path do %><%= fa_icon "tachometer" %> Dashboard <% end %>
        </li> 
         <% if can?(:read, User) %>
          <li class="nav-heading">
            <span data-bs-toggle="collapse" data-bs-target="#collapse-menu-administracao" aria-expanded="false">
              <%= fa_icon "gear" %> Administração <i class="fa fa-angle-down arrow"></i>
            </span>
            <ul class="collapse collapsed" id="collapse-menu-administracao">
              <% if can? :read, User %><li><%= link_to admin_users_path do %><em class="fa fa-caret-right"></em> <span>Usuários</span><% end %></li><% end %>
            </ul>
          </li>
        <% end %>
        <% if can?(:read, Question) || can?(:read, Questionnaire) || can?(:read, Dimension) %>
          <li class="nav-heading">
            <span data-bs-toggle="collapse" data-bs-target="#collapse-menu-cadastro-questionarios" aria-expanded="false">
              <%= fa_icon "file" %> Cadastro de Questionário <i class="fa fa-angle-down arrow"></i>
            </span>
            <ul class="collapse collapsed" id="collapse-menu-cadastro-questionarios">
              <% if can? :read, Question %><li><%= link_to admin_questions_path do %><em class="fa fa-caret-right"></em> <span>Questões</span><% end %></li><% end %>
              <% if can? :read, Questionnaire %><li><%= link_to admin_questionnaires_path do %><em class="fa fa-caret-right"></em> <span>Questionários</span><% end %></li><% end %>
              <% if can? :read, Dimension %><li><%= link_to admin_dimensions_path do %><em class="fa fa-caret-right"></em> <span>Dimensões</span><% end %></li><% end %>
            </ul>
          </li>
        <% end %>
        <% if can?(:read, QuestionnairePeriod) || can?(:manage, :report) %>
          <li class="nav-heading">
            <span data-bs-toggle="collapse" data-bs-target="#collapse-q-period-application" aria-expanded="false">
              <%= fa_icon "calendar" %> Periodo de Aplicação  <i class="fa fa-angle-down arrow"></i>
            </span>
            <ul class="collapse collapsed" id="collapse-q-period-application">
              <% if can? :read, QuestionnairePeriod %><li><%= link_to admin_questionnaire_periods_path do %><em class="fa fa-caret-right"></em> <span>Períodos</span><% end %></li><% end %>
            </ul>
          </li>
          <li class="nav-heading">
            <span data-bs-toggle="collapse" data-bs-target="#collapse-menu-relatorios" aria-expanded="false">
              <%= fa_icon "bar-chart" %> Relatórios <i class="fa fa-angle-down arrow"></i>
            </span>
            <ul class="collapse collapsed" id="collapse-menu-relatorios">
              <% if can? :read, :report %><li><%= link_to admin_reports_path do %><em class="fa fa-caret-right"></em> <span>Relatórios</span><% end %></li><% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</aside>

app/views/admin/modals/_modal_loading.html.erb
<div class="modal fade" id="modal_loading" tabindex="-1" role="dialog" aria-hidden="true" style="max-width: 100%; max-height: 100%;">
	<div class="modal-dialog modal-12" style="height: 90%;">
		<div class="loading_modal" ></div>
  </div>
</div>
<header>
	<style type="text/css">
		.loading_modal {
		    position: relative;
		    width: 250px;
		    height: 250px;
		    top: 40%;
		    left: 40%;
		    border-radius: 300px;
		    box-shadow: 0 10px 0 0 #49b8ef;
		    -ms-animation: uil-ring-anim 1s linear infinite;
		    -moz-animation: uil-ring-anim 1s linear infinite;
		    -webkit-animation: uil-ring-anim 1s linear infinite;
		    -o-animation: uil-ring-anim 1s linear infinite;
		    animation: uil-ring-anim 1s linear infinite;
		}
	</style>
</header>

app/views/admin/reports/_courses_partial.html.erb
<div class="row">
  <div col-12>
    <%= label_tag :course_id %>
    <%= select_tag :course_id, options_for_select(@courses.map{|c| [ c.course, c.course, data: { url: general_data_admin_reports_path(@questionnaire_period.id, course: c.course) }]}, params[:course]), remote: true, include_blank: 'Todos', class: 'form-control chosen-select' %>
  </div>
</div>

<div id="general_data"></div>

<script type="text/javascript">
  var CoursesPartial = {
    initialize: function() {
      $("#course_id").change(function(i, element){
        loading.show();
        if ($("#course_id").val() == "") {
          var url = '<%= general_data_admin_reports_path(@questionnaire_period.id) %>';
        } else {
          var url = $(this).children(':selected').data('url');
        }
        $.get(url).always(function(response){
          loading.hide()
        });
      });
      $("#course_id").trigger('change');
    }
  };
  CoursesPartial.initialize();
</script>

app/views/admin/reports/courses.js.erb
$('#courses').html('<%= j render partial: 'courses_partial', locals: { courses: @courses } %>');
$("#course_id").chosen({
  no_results_text: "Nenhum resultado sobre",
  multiple_text: "",
  placeholder_text_single: " ",
  allow_single_deselect: true,
  search_contains: true,
  width: "100%"
});

app/views/admin/reports/general_data.js.erb
$('#general_data').html('<%= j render partial: 'general_details_partial', locals: { courses: @courses } %>');

app/views/admin/users/add_user_context.js.erb
$('#tab-contexts').html('');
$("#tab-contexts").html("<%= j render partial: 'admin/users/partials/tab_contexts', locals: { user: @user } %>");

app/views/admin/users/edit.html.erb
<% title t('views.users.form.edit') %>

<%= render 'form', user: @user, read_only: false %>

app/views/admin/users/index.html.erb
<% title t('views.users.index.id') %>

<%= render 'admin/layouts/partials/messages' %>

<div class="alert alert-warning">
  <strong><%= t('views.responses.attention') %></strong> <%= t('views.responses.attention_message') %>
</div>

<div class="row">
  <div class="col-4 col-md-6 col-lg-7 col-xl-8">
    <% if can? :create, User %><%= link_to new_admin_user_path, class: 'btn btn-labeled btn-primary' do %><span class="btn-label"><i class="fa fa-plus"></i></span> <%= t('views.buttons.new') %> <% end %><% end %>
  </div>
  <div class="col-8 col-md-6 col-lg-5 col-xl-4">
    <%= form_tag(admin_users_path, method: 'get', id: 'users-default-search-form') do %>
      <div class="input-group">
        <%= text_field_tag :s, params[:s], class: 'form-control', placeholder: t('views.buttons.search_id'), autofocus: true %>
        <div class="input-group-append btn-group with-border">
          <%= button_tag class: 'btn btn-success', name: '' do %><i class="fa fa-search"></i><% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="card">
  <table class="table table-striped table-hover" id="usuarios-table" data-toggle="tableify">
    <thead>
      <tr>
        <th width="20" class="text-center"><i class="fa fa-ellipsis-v"></i></th>
        <th width="50" class="text-center"><%= User.human_attribute_name :active %></th>
        <th width="100"><%= User.human_attribute_name :login %></th>
        <th><%= User.human_attribute_name :name %></th>
        <th><%= User.human_attribute_name :email %></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td width="50" class="tableify-actions">
            <% if cannot?(:update, User) || can?(:read, User && user.uid.present?) %><%= link_to admin_user_path(user), class: 'tableify-default-action' do %><i class="fa fa-eye"></i> <%= t('views.buttons.view') %><% end %><% end %>
            <% if !user.uid.present? %>
              <% if can? :update, User %><%= link_to edit_admin_user_path(user), class: 'tableify-default-action', data: { modal: true } do %><i class="fa fa-pencil"></i> <%= t('views.buttons.edit')%><% end %><% end %>
              <% if can? :destroy, User %><%= link_to admin_user_path(user), method: :delete, data: { confirm: t('views.buttons.confirm_delete') } do %><i class="fa fa-trash"></i> <%= t('views.buttons.delete') %><% end %><% end %>
            <% end -%>
          </td>
          <td width="40" class="text-center"><%= user.active? %></td>
          <td><%= user.decorate.login %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th colspan="5"><%= page_entries_info @users %></th>
      </tr>
    </tfoot>
  </table>
</div>

<%= will_paginate @users, list_classes: %w[pagination justify-content-center mt-lg], inner_window: 1 %>

app/views/admin/users/new.html.erb
<% title t('views.users.form.edit') %>

<%= render 'form', user: @user, read_only: false %>